version: '3.7'
services:
  db:
    image: mongo:4.2.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: crossmap
      MONGO_INITDB_ROOT_PASSWORD: crossmap
    command: ["--bind_ip_all"]
    ports:
      - 8097:27017
    volumes:
      - ./mongodb-data:/data/db
    networks:
      crossmapNetwork:

  test:
    image: crossmap
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
    command: python3.7 -m unittest
    depends_on:
      - db
    ports:
      - 8098:8098
    networks:
      crossmapNetwork:

networks:
  crossmapNetwork:

