version: '3.7'
services:
  mongodb:
    image: mongo:4.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 8097:27017
    volumes:
      - ./docker-data:/data/db
